name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Plugin
        - Plugin Enhancement
        - Workflow Improvement
        - Documentation
        - Testing/CI/CD
        - Other
    validations:
      required: true

  - type: input
    id: plugin
    attributes:
      label: Related Plugin (if applicable)
      description: Which plugin does this relate to?
      placeholder: plugin-dev, llmstxt, etc.
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Currently, it's difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
      placeholder: I'd like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: I considered using X, but...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples or Use Cases
      description: Provide examples of how this would be used
      placeholder: |
        For example, when I'm...
        I would use this feature to...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this?
      options:
        - label: I'm willing to submit a PR for this feature
          required: false
